version: "0.2"
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 832689825609.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - docker build -t $ImageName -f Dockerfile .
      - docker images
  post_build:
    commands:
      - docker tag $ImageName:latest 832689825609.dkr.ecr.us-east-2.amazonaws.com/$ImageName:latest
      - docker push 832689825609.dkr.ecr.us-east-2.amazonaws.com/$ImageName:latest