version: 0.2

phases:
  install:
    commands:
      - echo "Cambiando al directorio backend-w/"
      - cd backend-w
      - echo "Logeando en Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 832689825609.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo "Construyendo imagen Docker desde backend-w..."
      - docker build -t backend-app .
      - docker tag backend-app:latest 832689825609.dkr.ecr.us-east-2.amazonaws.com/backend-app:latest
  post_build:
    commands:
      - echo "Enviando imagen a ECR..."
      - docker push 832689825609.dkr.ecr.us-east-2.amazonaws.com/backend-app:latest
